apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-ca-issuer
  namespace: staging
spec:
  acme:
    solvers:
      - dns01:
          cloudDNS:
            project: staging-452306
            hostedZoneName: 'tecsolution'
        selector:
          dnsZones:
            - 'tecsolution.solutions'  
