apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backendconfig
  namespace: staging
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 80
