apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-ca-issuer
  namespace: staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # production issuer
    email: abhimanyushahi88@gmail.com # required to register account
    privateKeySecretRef:
      name: prod-key
    solvers:
      - dns01:
          cloudDNS:
            project: staging-452306 # The ID of the GCP project
            hostedZoneName: 'tecsolution'
        selector:
          dnsZones:
            - 'tecsolution.solutions'  # ✅ Correct domain name
